WebApplication1/Controllers/BasketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebShop.Service.Interfaces;

namespace WebApplication.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;

        public BasketController(IBasketService basketService)
        {
            _basketService = basketService;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Detail()
        {
            var response = await _basketService.GetItems(User.Identity.Name);
            if (response.StatusCode == WebShop.Domain.Enum.StatusCode.OK)
            {
                return View(response.Data.ToList());
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> GetItem(Guid id)
        {
            var response = await _basketService.GetItem(User.Identity.Name, id);
            if (response.StatusCode == WebShop.Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using WebShop.Domain.ViewModels.Product;
using WebShop.Service.Interfaces;

namespace WebApplication.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetProducts()
        {
            var response = await _productService.GetProducts();

            if (response.StatusCode == WebShop.Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }

            return RedirectToAction("Error");
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetProduct(Guid id)
        {
            var response = await _productService.GetProduct(id);

            if (response.StatusCode == WebShop.Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }

            return RedirectToAction("Error");
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetProductsByType(string id)
        {
            var response = await _productService.GetProductsByType(id);

            if (response.StatusCode == WebShop.Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }

            return RedirectToAction("Error");
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetProductByName(string name)
        {
            var response = await _productService.GetProduct(name);

            if (response.StatusCode == WebShop.Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }

            return RedirectToAction("Error");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteProduct(Guid id)
        {
            var response = await _productService.DeleteProduct(id);

            if (response.StatusCode == WebShop.Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("GetProducts");
            }

            return View("Error", $"{response.DescriptionError}");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SaveProduct(Guid id)
        {
            if (id == Guid.Empty)
                return PartialView();

            var response = await _productService.GetProduct(id);

            if (response.StatusCode == WebShop.Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            ModelState.AddModelError("", response.DescriptionError);
            return PartialView();
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SaveProduct(ProductCreateViewModel productViewModel)
        {
            ModelState.Remove("Id");
            ModelState.Remove("DateCreate");
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error");
            }

            var product = await _productService.GetProduct(productViewModel.ID);

            if (product.Data == null)
            {
                await _productService.CreateProduct(productViewModel);
            }


            else
                await _productService.Edit(productViewModel);

            return RedirectToAction("GetProducts");
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> SearchString(string searchString)
        {
            if (searchString == null)
                return NotFound();

            var products = await _productService.SearchProduct(searchString.ToLower());


            return View("GetProducts", products.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public JsonResult GetTypes()
        {
            var types = _productService.GetTypes().Result;
            return Json(types.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public JsonResult GetCountrys()
        {
            var types = _productService.GetCountrys().Result;
            return Json(types.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public JsonResult GetManufactures()
        {
            var types = _productService.GetManufactures().Result;
            return Json(types.Data);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Строй маркет</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <link href="https://raw.githack.com/ttskch/select2-bootstrap4-theme/master/dist/select2-bootstrap4.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/backgroundImage.css" />
    <link rel="stylesheet" href="~/css/menu.css" />
    <link rel="stylesheet" href="~/css/paragraph.css" />
    <link rel="stylesheet" href="~/css/card.css" />
    <link rel="stylesheet" href="~/css/label.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

</head>
<body class="backgroundImage">
    <header>
        <nav class="navbar navbar-expand-lg" style="background-color: white;">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><span style="color:black; font-family:Impact; font-size:30px; background-color:white; border-radius:10px;">Stroy Market</span></a>
            <button class="navbar-toggler badge-light" style="border-radius:10px;" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-down-square-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm4 4a.5.5 0 0 0-.374.832l4 4.5a.5.5 0 0 0 .748 0l4-4.5A.5.5 0 0 0 12 6H4z" />
                </svg>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle paragraphLayout active text-black" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-family:'Comic Sans MS'; font-weight: bold;">
                                Аккаунт
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <ul class="nav flex-column paragraphHome">
                                                <li class="nav-item text-center">
                                                    <a class="nav-link active text-white" asp-controller="Account" asp-action="Register">
                                                        Регистрация
                                                    </a>
                                                </li>
                                                <li class="nav-item">
                                                    <a class="nav-link active text-white" asp-controller="Account" asp-action="Login">
                                                        Вход
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>

                    }
                    <form asp-controller="Product" asp-action="SearchString" method="get" class="form-inline my-2 my-lg-0" onsubmit="return validateSearchForm()">
                        <input class="form-control mr-sm-2" type="search" name="searchString" placeholder="Товар" aria-label="Search" required minlength="4">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
                    </form>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link paragraphLayout active text-black" asp-controller="Product" asp-action="GetProducts" style="font-family:'Comic Sans MS'; font-weight: bold;">
                                Товары
                            </a>
                        </li>

                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link paragraphLayout active text-black" style="font-family:'Comic Sans MS'; font-weight: bold;">
                                Админ
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link paragraphLayout active text-black" asp-controller="Product" asp-action="SaveProduct" style="font-family:'Comic Sans MS'; font-weight: bold;">
                                Добавить товары
                            </a>
                        </li>

                    }
                </ul>

                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-controller="Basket" asp-action="Detail">
                        <svg style="color: black;" xmlns="http://www.w3.org/2000/svg" width="37" height="37" fill="currentColor" class="bi bi-basket2-fill" viewBox="0 0 16 16">
                            <path d="M5.929 1.757a.5.5 0 1 0-.858-.514L2.217 6H.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h.623l1.844 6.456A.75.75 0 0 0 3.69 15h8.622a.75.75 0 0 0 .722-.544L14.877 8h.623a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1.717L10.93 1.243a.5.5 0 1 0-.858.514L12.617 6H3.383L5.93 1.757zM4 10a1 1 0 0 1 2 0v2a1 1 0 1 1-2 0v-2zm3 0a1 1 0 0 1 2 0v2a1 1 0 1 1-2 0v-2zm4-1a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0v-2a1 1 0 0 1 1-1z" />
                        </svg>
                    </a>

                    <a asp-controller="Account" asp-action="Edit">
                        <svg style="color: black;" xmlns="http://www.w3.org/2000/svg" width="44" height="44" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                        </svg>
                    </a>

                    <form method="get" asp-controller="Account" asp-action="Logout">
                        <input class="btn btn-danger rounded" style="font-family:'Comic Sans MS'; font-weight: bold; font-size:20px;" type="submit" value="Выход" />
                    </form>
                }
            </div>
        </nav>
    </header>
    <div class="container-fluid col-xl-12">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <div class="modal fade" id="modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Информация</h5>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-close btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    @if (User.IsInRole("Admin"))
                    {
                        <button type="button" class="btn btn-primary" id="saveBtn">Сохранить</button>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalWhButtons" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Информация</h5>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>


    <script>
        function validateSearchForm() {
            var searchString = document.getElementById("searchString").value;
            if (searchString.length < 4) {
                alert("Поисковый запрос должен содержать минимум 4 символа.");
                return false; // Отменить отправку формы
            }
            return true; // Продолжить отправку формы
        }
    </script>

    @await RenderSectionAsync("pageScripts", required: false)
</body>
</html>